### ISSUE TITLE
Bug report - Embeded Files don't have an 'open link' button

### ISSUE THREAD

**Issue by husterw** [GnoxNahte/obsidian-tab-panels#13]
### What happened?

Embedded files in tab panels don't have an 'open link' button.
![PixPin_2024-12-23_17-50-23](https://github.com/user-attachments/assets/7ab042f0-a25b-4937-aed6-bd95f78eaada)

### Sample Markdown

```tab-panels
--- Tab1
![[Test]]
--- Tab2
Hello World!
```

![[Test]]

### OS

Windows

**Comment by GnoxNahte** [comment]
Hey, thanks for the report!

I was able to reproduce it but unfortunately, the plugin doesn't explicitly render it. It just uses Obsidian's function: [MarkdownRenderer.render() ](https://docs.obsidian.md/Reference/TypeScript+API/MarkdownRenderer/render). I'll try to ask the Discord and see if anyone else faces the same issue.

**Comment by GnoxNahte** [comment]
I'll close this Issue as this isn't an issue related to this plugin. It's more of an Obsidian issue.

You can find this issue in other plugins. 
For example in Dataview, you can try this where it'll embed all files in the folder of the current note (Except the current note to prevent recurring embeds). 
````
```dataviewjs
dv.pages(`"${dv.current().file.folder}"`)
	.where(p => p.file.name != dv.current().file.name)
	.forEach(i => 
		{
			dv.header(1, 
				dv.paragraph("![[" + i.file.link.path + "]]")
			);
		});
```
````
