### ISSUE TITLE
Change mouse cursor type to "pointer" when hover on tab name

### ISSUE THREAD

**Issue by dsaperov** [GnoxNahte/obsidian-tab-panels#16]
Currently when hovering on tab name the cursor belongs to "text" type:
![image](https://github.com/user-attachments/assets/e532c4d2-c3c7-41fa-88ac-30aea2018bfa)

I want to propose to make it a "pointer" (a hand) type, because tabs are clickable and for me it's more familiar to see a "pointer" cursor on such elements.

Just my thoughts. If you consider current cursor type a better choice, I have nothing against it)

**Comment by GnoxNahte** [comment]
Sure nice suggestion. It'll be easy to add too.

But since it's a minor quality-of-life improvement, I'll push an update during the next update. 

I'll add a CSS snippet here if you want to copy it to your vault... I'll edit this away when I complete it

**Comment by dsaperov** [comment]
Great, thanks!
