### ISSUE TITLE
Tabs within tabs

### ISSUE THREAD

**Issue by jcesguerram** [GnoxNahte/obsidian-tab-panels#2]
Hi! It's me again. 

It would be great if you could add the possibility of adding tabs within tabs (in other words, nested tabs)

**Comment by GnoxNahte** [comment]
Added it! Changed the logic slightly, please test and see if it's ok!

**Comment by jcesguerram** [comment]
> Added it! Changed the logic slightly, please test and see if it's ok!

Fantastic, thnaks!
What's the code for th nested tabs?

**Comment by GnoxNahte** [comment]
Use the same syntax! Just put the code markup with the content inside. Remember to put the 'language' for the markdown (default is `tab-panels`) and `--- Tab name` 
<img width="721" alt="image" src="https://github.com/user-attachments/assets/5b1a9113-375b-47f3-8ff1-b9cd56f9f950">

It should look like this ^

I can't paste the markdown I used as GitHub will convert it to a code block. So just try to reference from the screenshot

**Comment by jcesguerram** [comment]
Ah got it!
I manged to do it, it looks great!
