### ISSUE TITLE
Links inside the tabs need to be considered also as outlinks and backlinks

### ISSUE THREAD

**Issue by zuwf** [GnoxNahte/obsidian-tab-panels#3]
Currently the wiki links inside the tab panels are not considered as outlinks and backlinks..

I am using rich foot to track the backlinks of the current note.. and links cited inside tabs are not displayed then I came to know those not taken as links by obsidian.. and it's only a rendering

**Comment by GnoxNahte** [comment]
Hi, thanks for the feature request!

I tried it for a while and can't seem to make it work though. Do you know of any plugins which are able to add backlinks? So that I can reference how they did it? I might ask the discord if anyone knows tomorrow.

**Comment by GnoxNahte** [comment]
Hey, I finally released the update for this feature. It took a bit longer than expected but it's finally done.

Adding this feature also made a few other features possible like automatically updating renamed linked files. Please try it out and let me know if it works!

Note that before using, you need to:
1. Enable caching in the settings 
2. Build the plugin's cache by either:
    - Making an edit to the note you want added to the cache, or
    - Clicking the **Rebuild Cache** button in the settings

Here's the part from the [Changelog](https://github.com/GnoxNahte/obsidian-tab-panels/blob/main/CHANGELOG.md#111-2024-12-07) that's related to this issue:

### **(Experimental)** Added [caching](../../#cache-experimental).
What caching does:
- Enables Obsidian to process data inside the tabs panel, just like regular markdown.
- Fully integrates **links, headings, and tags** within tab panels into Obsidian's core features (such as backlinks, outgoing links and graph view) and other plugins that use it like [Dataview](https://github.com/blacksmithgu/obsidian-dataview)
- Supports renaming linked files inside tab panels

> [!WARNING]
> Since it's quite a large feature, I've released it as an _experimental_ feature.
> If you find any bugs, please create an [issue](https://github.com/GnoxNahte/obsidian-tab-panels/issues/new?template=bug-report.yml).

Check the [README](../../#cache-experimental) for more info.

**Comment by zuwf** [comment]
Works very well..
Tested all scenarios and all of them passed on installing from BRAT

**Comment by GnoxNahte** [comment]
Nice! I haven't tried BRAT yet but I guess it should be the same as Obsidian's directory. Well as long as it works it's great.
