### ISSUE TITLE
Supports syntax similar to MkDocs' Content tabs

### ISSUE THREAD

**Issue by epleone** [GnoxNahte/obsidian-tab-panels#6]
### Is your feature request related to a problem? Please describe.

I use [MkDocs](https://squidfunk.github.io/mkdocs-material/blog/) to publish my Obsidian notes, More details are available on [obsidian-publish-mkdocs](https://github.com/jobindjohn/obsidian-publish-mkdocs).

Could you support syntax similar to [MkDocs' Content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#content-tabs) ?

### Describe the solution you'd like

![](https://forum.obsidian.md/uploads/default/original/3X/4/8/48dfe3b602d19770cc3e4769c8bbd3641ce353f4.png)

**Comment by GnoxNahte** [comment]
Sure, I think it should be doable. I'm currently working on another feature and hope to finish by tomorrow. Then, I'll do this feature and release it in the next version!
