### ISSUE TITLE
Tabs in rows but not in columns

### ISSUE THREAD

**Issue by CelineRichard-Molard** [GnoxNahte/obsidian-tab-panels#8]
### What happened?

Hello,
When I use the plugin, the tabs are created correctly but appear on top of each other instead of next to each other as in the demo. I tried to change the appearance theme but it doesn't change anything. Maybe I am doing something wrong !

### Sample Markdown

~~~tabs
--- A finaliser
- Etiquettes nouveaux colorants
- Montage
 
--- Savons à faire
- [ ] Mon ange
- [ ] Crepuscule

~~~

### Errors

no error

### OS

MacOS

**Comment by GnoxNahte** [comment]
Hi, can you send a screenshot so I can see what it looks like?

Also did you try the default obsidian theme? 

If it works in the default theme, can you send the theme that you used so I can try to replicate it on my side?

**Comment by CelineRichard-Molard** [comment]
Here are some screenshots : 
- The first one is with the AnuPpuccin Theme that I am using
- The second is with the default obsidian theme
As you can see, it is basically the same problem with both. 

Thank you for your helps, I'd really like to use your wonderful plugin !

![Capture d’écran 2024-12-08 à 10 56 40](https://github.com/user-attachments/assets/2372fb9e-bb5f-45c9-aa53-0bb70bc05169)
![Capture d’écran 2024-12-08 à 10 58 52](https://github.com/user-attachments/assets/bc20dadf-62bf-4f41-a6e5-c6c55bf6f2e7)

**Comment by GnoxNahte** [comment]
That's weird... I tried it on my friend's Mac with a fresh install of Obsidian and it works fine so it's not a Mac problem.

Some other reasons that might be interfering with the styles:
- Do you have any [CSS Snippets](https://help.obsidian.md/Extending+Obsidian/CSS+snippets)? If you have, could you try disabling it?
- Maybe some plugin is modifying the styles? To test if this is the case, try one of these:
  - Disable all plugins except this one and reload Obsidian. If it works, turn back each plugin one by one to find out which plugin is interfering with it.
  - Create a fresh vault and install the plugin to test.

If it still doesn't work, try adding these lines into [CSS Snippets](https://help.obsidian.md/Extending+Obsidian/CSS+snippets#:~:text=To%20add%20a,in%20the%20list.)
```css
ul.tab-container {
    display: flex !important;
    flex-direction: row !important;
}
```

Thanks for your patience and support! I'll try to help as much as possible to solve this issue!

**Comment by CelineRichard-Molard** [comment]
Eureka, I've found the problem! 
In fact, it was a double problem: the Style Setting plugin caused the first problem. As soon as I deactivated it, the tabs displayed correctly. 
Then I reactivated the Style Setting plugin and tried to disable the snippets I use. And I found that the CSS snippet 'S-Image- Adjustments' also generates tab display problems. 
To summarize: 
- CSS Snippet "S-Image Adjustment" ON and plugin Style Setting OFF = it works
- CSS Snippet "S-Image Adjustment" OFF and plugin Style Setting ON = it works
- CSS Snippet "S-Image Adjustment" ON and plugin Style Setting ON = it doesn't work

You can find the code for CSS Snippet "S-Image Adjustment" here : https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/Snippets/S%20-%20Images%20Adjustments.css

**Comment by GnoxNahte** [comment]
Nice! Good job finding the problem :)

So I tried the styles and looked over the code. Here's some changes to make if you want to continue using CSS snippets and the tabs plugin:

### Making the tabs line up horizontally
Replace the last line with this:
```css
.img-adj-list :is(ul, ol):not(.tab-container) {
  display: flow-root;
}
```

### Removing extra spacing
Not sure if you have, but if you do have some spacing, like in the screenshot, 
![image](https://github.com/user-attachments/assets/1cfb0a69-88b9-40b5-b8cf-bbf598c6f5f7)
Add this in any CSS snippet file.
```css
.markdown-rendered ul.tab-container {
  margin-block-start: 0;
  margin-block-end: 0;
}
```
Note that I'm planning to make a way for users to modify the styles and the CSS style above might overwrite it. If you want to modify the styles, just comment here again and I'll help you with that.

Let me know if it works!

**Comment by CelineRichard-Molard** [comment]
Yes it works ! I can now activate the plugin and the snippets together. 
No problem with space on my computer. 
Thank you again for your help !
